version: "3.8"

services:
  db:
    image: ankane/pgvector
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: rag_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "postgres" ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 20s

  ollama:
    image: ollama/ollama
    ports:
      - "11434:11434"
    volumes:
      - ./ollama-entrypoint.sh:/ollama-entrypoint.sh
    entrypoint: [ "/bin/bash", "/ollama-entrypoint.sh" ]
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:11434" ]
      interval: 15s
      timeout: 10s
      retries: 15
      start_period: 60s

  app:
    build: .
    depends_on:
      db:
        condition: service_healthy
      ollama:
        condition: service_healthy
    ports:
      - "8000:8000"
      - "8501:8501"
    environment:
      DATABASE_URL: postgresql+psycopg2://postgres:postgres@db:5432/rag_db
      OLLAMA_HOST: ollama:11434
    volumes:
      - .:/app
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8000/health" ]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s
    command: [ "/bin/bash", "/app/entrypoint.sh" ]

volumes:
  pgdata:
