version: "3.8"

services:
  db:
    image: ankane/pgvector
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: rag_db
    ports:
      - "5432:5432"

  ollama:
    image: ollama/ollama
    ports:
      - "11434:11434"

  app:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db
      - ollama
    environment:
      DATABASE_URL: postgresql+psycopg2://postgres:postgres@db:5432/rag_db
